package com.example.demo.service;

import com.example.demo.model.RideRequest;
import com.example.demo.model.RouteSchedule;
import com.example.demo.repository.RideRequestRepository;
import com.example.demo.repository.RouteScheduleRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.TextStyle;
import java.util.List;
import java.util.Locale;

@Service
@EnableScheduling
public class SchedulerService {

    private static final Logger log = LoggerFactory.getLogger(SchedulerService.class);

    @Autowired private RouteScheduleRepository scheduleRepo;
    @Autowired private RouteScheduleService scheduleService;
    @Autowired private RideRequestRepository rideRepo;
    @Autowired private NotificationService notifService;

    /** Runs every day at 6:00 AM — generates rides from active schedules. */
    @Scheduled(cron = "0 0 6 * * *")
    public void autoGenerateDailyRides() {
        String today = LocalDate.now()
            .getDayOfWeek()
            .getDisplayName(TextStyle.SHORT, Locale.ENGLISH)
            .toUpperCase()
            .substring(0, 3);

        List<RouteSchedule> active = scheduleRepo.findByIsActiveTrue();
        int generated = 0;
        for (RouteSchedule s : active) {
            if (s.getDaysOfWeek() != null && s.getDaysOfWeek().contains(today)) {
                try {
                    scheduleService.generateRide(s.getId());
                    generated++;
                } catch (Exception e) {
                    log.warn("Failed to auto-generate ride for schedule #{}: {}", s.getId(), e.getMessage());
                }
            }
        }
        log.info("Auto-generated {} rides for {} ({})", generated, today, LocalDate.now());
    }

    /**
     * Runs every hour — cancels PENDING rides whose scheduled time has passed
     * by more than 2 hours with no driver action.
     */
    @Scheduled(cron = "0 0 * * * *")
    public void autoCancelExpiredRides() {
        LocalDateTime cutoff = LocalDateTime.now().minusHours(2);
        List<RideRequest> pending = rideRepo.findByStatus("PENDING");
        int cancelled = 0;

        for (RideRequest ride : pending) {
            try {
                if (ride.getRideDate() == null || ride.getRideTime() == null) continue;
                LocalDate date = LocalDate.parse(ride.getRideDate());
                LocalTime time = LocalTime.parse(ride.getRideTime());
                LocalDateTime scheduled = LocalDateTime.of(date, time);
                if (scheduled.isBefore(cutoff)) {
                    ride.setStatus("CANCELLED");
                    rideRepo.save(ride);
                    cancelled++;

                    // Notify the driver
                    if (ride.getUser() != null) {
                        try {
                            notifService.send(
                                ride.getUser().getId(),
                                "Ride Auto-Cancelled",
                                "Your ride from " + ride.getSourceLocation() + " on "
                                    + ride.getRideDate() + " was cancelled as it passed without confirmation.",
                                "SYSTEM"
                            );
                        } catch (Exception ignored) {}
                    }
                }
            } catch (Exception e) {
                log.warn("Could not process ride #{} for auto-cancel: {}", ride.getId(), e.getMessage());
            }
        }

        if (cancelled > 0)
            log.info("Auto-cancelled {} expired PENDING rides", cancelled);
    }
}
